name: PARABLE
favicon: null
layout_spectrum: 0.17355704540386796
typography_spectrum: 0.4354620634112507
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.12349826819263399
  lightness: 0.6428657479118556
  saturation: 0.8833348064217716
  rhythmicContrast: 0.292063576169312
purpose: []
